[FIX] Missing one line causes a link error
WoonKyong/2022_alpr_6 pull request #1
Opened 2022-06-15 09:59 UTC by spa46

위 변경 사항 없이는 링크 에러가 발생하네요
배포 이후 중간에 업데이트가 됐을 것 같습니다만...

2022-06-22 05:47 UTC, WoonKyong approved these changes

2022-06-22 11:58 UTC, ddonyo approved these changes

2022-06-23 00:29 UTC, WoonKyong requested changes
LGTM

2022-06-23 00:29 UTC, merged

2022-06-23 00:32 UTC, WoonKyong reviewed
LGTM